first draft of xalgo consensus
Folks-Finance/folks-finance-js-sdk pull request #47
Opened 2024-08-23 11:40 UTC by gidonkatten

2024-08-23 13:23 UTC, stefanofa requested changes

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/allocationStrategies/greedy.ts
> +  const strategy = new Array<bigint>(proposersBalances.length);
```suggestion
  const allocations = new Array<bigint>(proposersBalances.length);
```

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/allocationStrategies/greedy.ts
> +  const strategy = new Array<bigint>(proposersBalances.length);
```suggestion
  const allocations = new Array<bigint>(proposersBalances.length);
```

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/types.ts
> +type ProposerAllocation = bigint[];
Maybe it is better to call it:
`ProposerAllocations` in plural?

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultStakeAllocationStrategy(consensusState, amount),
```suggestion
  proposerAllocations = defaultStakeAllocationStrategy(consensusState, amount),
```

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultStakeAllocationStrategy(consensusState, amount),
```suggestion
  proposerAllocations = defaultStakeAllocationStrategy(consensusState, amount),
```

2024-08-23 13:23 UTC, stefanofa commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultUnstakeAllocationStrategy(consensusState, amount),
```suggestion
  proposerAllocations = defaultUnstakeAllocationStrategy(consensusState, amount),
```

2024-08-23 13:26 UTC, gidonkatten commented on src/xAlgo/allocationStrategies/greedy.ts
> +  const strategy = new Array<bigint>(proposersBalances.length);
cf950281a5de8984785b4be0be8b68d2ec854f6d

2024-08-23 13:26 UTC, gidonkatten commented on src/xAlgo/allocationStrategies/greedy.ts
> +  const strategy = new Array<bigint>(proposersBalances.length);
cf950281a5de8984785b4be0be8b68d2ec854f6d

2024-08-23 13:29 UTC, gidonkatten commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultUnstakeAllocationStrategy(consensusState, amount),
549c611c0cb7e101c895cb8f15e274d4b41b5f93

2024-08-23 13:29 UTC, gidonkatten commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultStakeAllocationStrategy(consensusState, amount),
549c611c0cb7e101c895cb8f15e274d4b41b5f93

2024-08-23 13:29 UTC, gidonkatten commented on src/xAlgo/consensus.ts
> +  allocationStrategy = defaultStakeAllocationStrategy(consensusState, amount),
549c611c0cb7e101c895cb8f15e274d4b41b5f93

2024-08-23 13:29 UTC, gidonkatten commented on src/xAlgo/types.ts
> +type ProposerAllocation = bigint[];
549c611c0cb7e101c895cb8f15e274d4b41b5f93

2024-08-27 08:45 UTC, palace22 approved these changes

2024-08-29 09:40 UTC, stefanofa submitted a review, later dismissed

2024-08-29 10:19 UTC, merged